const REQUEST = '_REQUEST'
const SUCCESS = '_SUCCESS'
const FAILURE = '_FAILURE'

const CRAFTING_CLASS = 'CRAFTING_CLASS'
const RECIPE = 'RECIPE'

export const CRAFTING_CLASS_REQUEST = CRAFTING_CLASS + REQUEST
export const CRAFTING_CLASS_SUCCESS = CRAFTING_CLASS + SUCCESS
export const CRAFTING_CLASS_FAILURE = CRAFTING_CLASS + FAILURE

export const RECIPE_REQUEST = RECIPE + REQUEST
export const RECIPE_SUCCESS = RECIPE + SUCCESS
export const RECIPE_FAILURE = RECIPE + FAILURE
