// const LODESTONE = 'LODESTONE'
const LOCAL = 'LOCAL'

// const REQUEST = 'REQUEST'
// const SUCCESS = 'SUCCESS'
// const FAILURE = 'FAILURE'

export const LOCAL_CLASS_DATA_RETRIEVAL = `${LOCAL}_CLASS_DATA_RETRIEVAL`
export const LOCAL_CHARACTER_DATA_RETRIEVAL = `${LOCAL}_CHARACTER_DATA_RETRIEVAL`
