const REQUEST = '_REQUEST'
const SUCCESS = '_SUCCESS'
const FAILURE = '_FAILURE'

const CRAFTING_CLASS = 'CRAFTING_CLASS'

export const CRAFTING_CLASS_REQUEST = `${CRAFTING_CLASS}${REQUEST}`
export const CRAFTING_CLASS_SUCCESS = `${CRAFTING_CLASS}${SUCCESS}`
export const CRAFTING_CLASS_FAILURE = `${CRAFTING_CLASS}${FAILURE}`
