const REQUEST = '_REQUEST'
const SUCCESS = '_SUCCESS'
const FAILURE = '_FAILURE'

const CRAFTING_CLASS = 'CRAFTING_CLASS'
const RECIPE_LIST = 'RECIPE_LIST'

export const CRAFTING_CLASS_REQUEST = CRAFTING_CLASS + REQUEST
export const CRAFTING_CLASS_SUCCESS = CRAFTING_CLASS + SUCCESS
export const CRAFTING_CLASS_FAILURE = CRAFTING_CLASS + FAILURE

export const RECIPE_LIST_REQUEST = RECIPE_LIST + REQUEST
export const RECIPE_LIST_SUCCESS = RECIPE_LIST + SUCCESS
export const RECIPE_LIST_FAILURE = RECIPE_LIST + FAILURE

export const CLEAR_RECIPE_LIST = 'CLEAR_RECIPE_LIST'
