const REQUEST = 'REQUEST'
const SUCCESS = 'SUCCESS'
const FAILURE = 'FAILURE'

const API_REQUEST = 'API_REQUEST'

export const API_REQUEST_SUCCESS = `${API_REQUEST}_${SUCCESS}`
export const API_REQUEST_FAILURE = `${API_REQUEST}_${FAILURE}`

export const FETCH_RECIPES_BY_ID = 'FETCH_RECIPES_BY_ID'
export const SEARCH_RECIPES = 'SEARCH_RECIPES'
