const RECIPE_SEARCH = 'RECIPE_SEARCH'
const RECIPE_LIST = 'RECIPE_LIST'
const SHOPPING_LIST = 'SHOPPING_LIST'

export const RECIPE_SEARCH_REQUEST = `${RECIPE_SEARCH}_SEARCH`
export const RECIPE_SEARCH_SUCCESS = `${RECIPE_SEARCH}_SUCCESS`
export const RECIPE_SEARCH_FAILURE = `${RECIPE_SEARCH}_FAILURE`
export const RECIPE_SEARCH_CLEAR = `${RECIPE_SEARCH}_CLEAR`

// export const RECIPE_LIST_ADD = `${RECIPE_LIST}_ADD`
// export const RECIPE_LIST_REMOVE = `${RECIPE_LIST}_REMOVE`
export const RECIPE_LIST_CLEAR = `${RECIPE_LIST}_CLEAR`
export const RECIPE_LIST_SAVE = `${RECIPE_LIST}_SAVE`

export const SHOPPING_LIST_CREATE = `${SHOPPING_LIST}_CREATE`
export const SHOPPING_LIST_CLEAR = `${SHOPPING_LIST}_CLEAR`
export const SHOPPING_LIST_ERROR = `${SHOPPING_LIST}_ERROR`
