const RECIPE_LIST = 'RECIPE_LIST'
const SHOPPING_LIST = 'SHOPPING_LIST'

// export const RECIPE_LIST_ADD = `${RECIPE_LIST}_ADD`
// export const RECIPE_LIST_REMOVE = `${RECIPE_LIST}_REMOVE`
export const RECIPE_LIST_CLEAR = `${RECIPE_LIST}_CLEAR`
export const RECIPE_LIST_SAVE = `${RECIPE_LIST}_SAVE`

export const SHOPPING_LIST_CREATE = `${SHOPPING_LIST}_CREATE`
export const SHOPPING_LIST_CLEAR = `${SHOPPING_LIST}_CLEAR`
